### ISSUE TITLE
无法提取数据

### ISSUE THREAD

**Issue by christineaa** [linhx25/FReader#1]
您好，我遇到了两个问题：
1. 直接调用包时出错
`
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
import FReader as FR #需要在同一文件夹下创建python文件

file_path = './BB_Docs_20200712_002013/20080401_RINO_10k_v109119_10k.htm'#选取文件路径
f = FR.FReader(file_path)#新建FReader对象

#选取item1 Business，所有的items都自动分类储存在_txts_dict字典里，按键值取出即可
item1 = f._txts_dict['item1']

#选取MD&A，即item 7
item7 = f._txts_dict['item7']

#计算 item 7 的 gunning fog index
fog = FR.Textstat().gunning_fog(item7)
print(fog)

#以FENG LI论文为例，分别计算FOG和Nlength两个统计量，为了方便把它放在FReader.Li()函数中
fog,length = f.li(item7)
`

报错：
AttributeError: module 'FReader' has no attribute 'FReader'

2. 我直接使用freader.py文件无法提取任何数据
我所使用的文件是：https://www.sec.gov/Archives/edgar/data/0001595761/000110465920052748/wb-20191231x20f.htm
2.1 我仔细看了一下发现几个问题，第一个是我用的20-F文件，每一小节的标题名不一样
2.2 create_txt()函数无法定位到文本，first_link是空值

**Comment by linhx25** [comment]
1. Please try code:
    from freader import freader
or in the same directory:
    import freader as FR

2. This code is not designed for 20-F file, the content is different from 10-K's. Changing the subtitles corresponding code might work.
